### ISSUE TITLE
Clipped Process Names

### ISSUE THREAD

**Issue by the-real-tokai** [sveinbjornt/Sloth#9] opened 2020-03-02 21:56 UTC
In some cases I see some process names getting clipped off at seemingly random positions, e.g. 'periodic-wrapper' shows up as 'periodic-wrappe', 'coresymbolicationd' as 'coresymbolicati', 'KernelEventAgent' as 'KernelEventAgen' and so on. It only seems to happen for a handful of processes, everything else seems to show up OK.

The 'Display Mac-friendly process names' option has no effect on the issue. Happens with it "on" and "off".

`Version 2.9 (225)`

**Comment by the-real-tokai** [comment] 2020-03-02 22:00
OK, putting those in a list with a monospaced font the cut off point is actually rather fixed after 15 characters:

```
KernelEventAgen
coresymbolicati
periodic-wrappe
```

**Comment by sveinbjornt** [comment] 2020-03-03 20:32
Could you tell me what version of macOS you are running?

**Comment by sveinbjornt** [comment] 2020-03-03 20:53
This is interesting. Lsof by default concatenates process names to 15 chars, but Sloth actually goes out of its way to look up the full process name in the kernel via PID. It should only fall back on lsof's 15 char name if kernel process lookup fails. For some reason, this is happening on your system. Perhaps these processes existed when lsof was contacting the kernel, but no longer existed when Sloth did?

**Comment by sveinbjornt** [comment] 2020-03-03 20:55
Ah, I've figured it out. You're running Sloth as root after unlocking. Lsof runs with root privileges, but the subsequent attempt at full kernel proc name lookup *does not*.  This is a tough one to solve without an expensive fork of a privileged tool... :/

**Comment by the-real-tokai** [comment] 2020-03-03 21:47
Correct, I clicked the "Lock" symbol and elevated it, so I could see the tasks I actually was looking for (they run under a different user). The "KernelEventAgen" is reproducible here.

https://external.binaryriot.org/site-github-com/sloth_kerneleventagen.png

I tested this on a "somewhat" outdated `Yosemite` box (`10.10.5`). :)

**Comment by sveinbjornt** [comment] 2020-03-03 21:54
OK, now the problem is clear, I don't really think it's worth fixing. It's too silly and expensive to fork full process name lookup to a privileged forked process, and the issue doesn't seem to affect Mojave or El Capitan. So closing. However, thank you very much for your feedback!

**Closed by sveinbjornt** 2020-03-03 21:54 UTC
